encoding: UTF-8

permalink: /:year/:month/:day/:title.html
paginate: 5
markdown: kramdown

kramdown:
  input: GFM

highlighter: rouge


# 作者信息
author: 
  name: 武广
  email: twistedwg@hotmail.com
  link: http://www.twistedwg.com/
  weibo: http://weibo.com/u/5261676762
  github: https://github.com/TwistedW
  github_username:  TwistedW
  weibo_username:  TwistedW

# 站点信息
title : TwistedW's Home
description: 
  喜欢跑步，经常跑5公里。喜欢在夜晚长跑，忘记一切烦恼和压力。
url: http://www.twistedwg.com/
rss_url: /feed.xml

# gavatar头像及Favicon
gavatar : /assets/img/logo.jpg
favicon : /assets/img/logo.png

# disqus 设置
#disqus:
#  shortname: blademastercoder

#profile 个人信息

profile_desc : 坚持学术与身体一起磨练<br> #QQ交流群：701451028<br>

# 首页除了最新文章外显示分类
cates: 
- Essay

# 中文本地化
locals: 
   newest : 最新文章